id: A19CAE9C2
title: In Praise of the Three Jewels
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:17:33.688264
  last_modified_at: 2022-03-01 02:17:33.688287
